function ms = mff_date_to_ms(str)
% MFF_DATE_TO_MS Convert a datestring to a serial date number
idxDecimal  = regexp(str, '\.');
idxTimeZone = regexp(str, '[+-][0-9]{2}:[0-9]{2}');
ms = 1000 * ( ...
         datenum(str(1:idxDecimal-1), 'yyyy-mm-ddTHH:MM:SS') * 24*60*60 + ...
         str2double(str(idxDecimal:idxTimeZone-1)) ...
     );
