function AddEEGLABPath(app)

KnownEEGLABLocs = { ...
    'S:\Sleep\SleepSoftware\eeglab\latest';
    '/Users/Mac-n-Cheese/Documents/Toolboxes/eeglab/13.6.5b';
    };
eeglabDir = which('eeglab');
if ~isempty(eeglabDir)
    % assume EEGLAB is already added to the path
    return
else
    for i = 1:length(KnownEEGLABLocs)
        if exist([KnownEEGLABLocs{i}, '/', 'eeglab.m'], 'file')
            eeglabDir = KnownEEGLABLocs{i};
            break
        end
    end
end
if ~isempty(eeglabDir)
    addpath(eeglabDir); eeglab; close all;
else
    sel = uiconfirm(app.UIFigure, 'EEGLAB is not added to the Matlab path. Please use the browse button to specify the path where ''eeglab.m'' is located', 'Question', ...
        'Options',{'Browse'},...
        'DefaultOption', 'Browse', ...
        'Icon', 'question'); %#ok<NASGU>
    eeglabDir = uigetdir('.', 'Specify the path where ''eeglab.m'' is located');
    if eeglabDir == 0 % User pressed cancel, so quit
        sel = uiconfirm(app.UIFigure, 'You pressed ''Cancel'', so I quit.', 'Info', ...
            'Options',{'Quit'},...
            'DefaultOption', 'Quit', ...
            'Icon', 'Info'); %#ok<NASGU>
        delete(app);
        return
    end
    if exist([eeglabDir, '/eeglab.m'], 'file') == 0
        sel = uiconfirm(app.UIFigure, ['''eeglab.m'' is not located in ''', eeglabDir,''', so I quit.'], 'Info', ...
            'Options',{'Quit'},...
            'DefaultOption', 'Quit', ...
            'Icon', 'Info'); %#ok<NASGU>
        delete(app);
        return
    else
        addpath(eeglabDir); eeglab; close all;
    end
end

% Set the option file to save all header files in version 7.3
pop_editoptions( ...
    'option_storedisk', 0, ...
    'option_savetwofiles', 1, ...
    'option_saveversion6', 0, ...
    'option_single', 1, ...
    'option_memmapdata', 0, ...
    'option_eegobject', 0, ...
    'option_computeica', 1, ...
    'option_scaleicarms', 1, ...
    'option_rememberfolder', 1, ...
    'option_donotusetoolboxes', 0, ...
    'option_checkversion', 1, ...
    'option_chat', 0);

end