% APPSIDEBAR
% Vertical menu on the left side of the application

% Authors:
%   Rick Wassing, Woolcock Institute of Medical Research, Sydney, Australia
%
% History:
%   Created 2025-02-21, Rick Wassing

% EEG-Processor (C) 2025 by Rick Wassing is licensed under CC BY-NC-SA 4.0.
% View the license at https://creativecommons.org/licenses/by-nc-sa/4.0

classdef AppSidebar < matlab.ui.componentcontainer.ComponentContainer
    % #####################################################################
    % PROPERTIES
    % =====================================================================
    % Public properties that users have access to
    properties (Access = public)
        state; % The component's state
    end
    % =====================================================================
    % Private properties for sub-component handles that users cannot access
    properties (Access = private, Transient, NonCopyable)
        comps; % Contains all handles to sub-components
    end
    % #####################################################################
    % METHODS
    % =====================================================================
    % Constructor
    methods
        function Obj = AppSidebar(parent, varargin)
            % Use the parent user-data to pass the varargin
            parent.UserData.tmp = varargin;
            Obj@matlab.ui.componentcontainer.ComponentContainer('Parent', parent);
        end
    end
    % =====================================================================
    % Private methods
    methods (Access = protected)
        % -----------------------------------------------------------------
        % Create the component
        function setup(Obj)
            try
                % Extract the varargin from the parent's user-data
                props = parsevarargin(Obj.Parent.UserData.tmp);
                % Create this component
                Obj.comps.Panel = uipanel(Obj, ...
                    'BorderType', 'none', ...
                    'BackgroundColor', props.style.colors.background.primary, ...
                    'Units', 'normalized', ...
                    'Position', [0, 0, 1, 1]);
                Obj.comps.GridLayout = uigridlayout(Obj.comps.Panel, ...
                    'BackgroundColor', props.style.colors.background.primary, ...
                    'ColumnWidth', {'1x'}, ...
                    'RowHeight', ...
                        [...
                            {props.style.logo.height}, ...
                            repmat({props.style.spacing.lg}, 1, 7), ...
                            {150} ...
                        ], ...
                    'Padding', [props.style.spacing.lg, props.style.spacing.lg, 0, props.style.spacing.lg], ...
                    'ColumnSpacing', 0, ...
                    'RowSpacing', props.style.spacing.sm);
                Obj.comps.Logo = uiimage(Obj.comps.GridLayout, ...
                    'ImageSource', 'logo.png', ...
                    'HorizontalAlignment', 'left', ...
                    'ScaleMethod', 'fit');
                % Create subcomponents
                Obj.createComponents(props);
            catch ME
                printerrormessage(ME, sprintf('The error occurred during ''setup'' in %s.', mfilename('class')))
            end
        end
        % -----------------------------------------------------------------
        % Update the component, is automatically executed when properties change.
        function update(Obj)
            try
                % Do something
            catch ME
                printerrormessage(ME, sprintf('The error occurred during ''update'' in %s.', mfilename('class')))
            end
        end
        % -----------------------------------------------------------------
        % Create sub-components
        function createComponents(Obj, props)
            % Render navigation buttons
            Obj.comps.nav(1).handle = uibutton(Obj.comps.GridLayout, ...
                'Text', 'DATABASE', ...
                'FontName', props.style.typography.base.font, ...
                'FontSize', props.style.typography.base.size, ...
                'FontWeight', props.style.typography.button.fontWeight, ...
                'FontColor', props.style.colors.button.dark, ...
                'HorizontalAlignment', 'left', ...
                'BackgroundColor', props.style.colors.background.primary, ...
                'Icon', 'icon-database-dark.png');
            Obj.comps.nav(2).handle = uibutton(Obj.comps.GridLayout, ...
                'Text', 'PARTICIPANTS', ...
                'FontName', props.style.typography.base.font, ...
                'FontSize', props.style.typography.base.size, ...
                'FontWeight', props.style.typography.button.fontWeight, ...
                'FontColor', props.style.colors.button.dark, ...
                'HorizontalAlignment', 'left', ...
                'BackgroundColor', props.style.colors.background.primary, ...
                'Icon', 'icon-group-dark.png');
            Obj.comps.nav(3).handle = uibutton(Obj.comps.GridLayout, ...
                'Text', 'SOURCEDATA', ...
                'FontName', props.style.typography.base.font, ...
                'FontSize', props.style.typography.base.size, ...
                'FontWeight', props.style.typography.button.fontWeight, ...
                'FontColor', props.style.colors.button.dark, ...
                'HorizontalAlignment', 'left', ...
                'BackgroundColor', props.style.colors.background.primary, ...
                'Icon', 'icon-folder-source-dark.png');
            Obj.comps.nav(4).handle = uibutton(Obj.comps.GridLayout, ...
                'Text', 'RECORDINGS', ...
                'FontName', props.style.typography.base.font, ...
                'FontSize', props.style.typography.base.size, ...
                'FontWeight', props.style.typography.button.fontWeight, ...
                'FontColor', props.style.colors.button.dark, ...
                'HorizontalAlignment', 'left', ...
                'BackgroundColor', props.style.colors.background.primary, ...
                'Icon', 'icon-activity-dark.png');
            Obj.comps.nav(5).handle = uibutton(Obj.comps.GridLayout, ...
                'Text', 'PHENOTYPES', ...
                'FontName', props.style.typography.base.font, ...
                'FontSize', props.style.typography.base.size, ...
                'FontWeight', props.style.typography.button.fontWeight, ...
                'FontColor', props.style.colors.button.dark, ...
                'HorizontalAlignment', 'left', ...
                'BackgroundColor', props.style.colors.background.primary, ...
                'Icon', 'icon-interests-dark.png');
            Obj.comps.nav(6).handle = uibutton(Obj.comps.GridLayout, ...
                'Text', 'PIPELINES', ...
                'FontName', props.style.typography.base.font, ...
                'FontSize', props.style.typography.base.size, ...
                'FontWeight', props.style.typography.button.fontWeight, ...
                'FontColor', props.style.colors.button.dark, ...
                'HorizontalAlignment', 'left', ...
                'BackgroundColor', props.style.colors.background.primary, ...
                'Icon', 'icon-mediation-dark.png');
            Obj.comps.nav(7).handle = uibutton(Obj.comps.GridLayout, ...
                'Text', 'PROCESSES (99+)', ...
                'FontName', props.style.typography.base.font, ...
                'FontSize', props.style.typography.base.size, ...
                'FontWeight', props.style.typography.button.fontWeight, ...
                'FontColor', props.style.colors.button.dark, ...
                'HorizontalAlignment', 'left', ...
                'BackgroundColor', props.style.colors.background.primary, ...
                'Icon', 'icon-run-dark.png');
        end
    end
end