function ax = plotTopoplot(ax, data, chanlocs, MarkerSize)

% When all values are zero, then 'topoplot' throws an
% error because the color limits are not incrementing,
% i.e. they are [0, 0], which is not allowed
data(isnan(data)) = 0;
if length(unique(data)) == 1
    if unique(data) == 0
        data(data == 0) = 0.0001;
    end
end
% Draw figure and topoplot
Fig = figure;
if MarkerSize == -1
    h = topoplot(data, chanlocs, ...
        'style', 'map', ...
        'electrodes', 'off', ...
        'plotrad', 1, ...
        'headrad', 0.6, ...
        'intrad', 1, ...
        'conv', 'on', ...
        'numcontour', 0, ...
        'hcolor', 'k', ...
        'whitebk', 'on');
else
    h = topoplot(data, chanlocs, ...
        'style', 'map', ...
        'electrodes', 'on', ...
        'plotrad', 1, ...
        'headrad', 0.6, ...
        'intrad', 1, ...
        'conv', 'on', ...
        'numcontour', 0, ...
        'emarker', {'.', 'w', MarkerSize, 1}, ...
        'emarker2', {1, '.', [0.110, 0.769, 0.824], MarkerSize+3, 1}, ...
        'hcolor', 'k', ...
        'whitebk', 'on');
end
% Copy objects to axes
copyobj(Fig.Children.Children, ax)
for j = 1:length(Fig.Children.Children)
    ax.Children(j).PickableParts = 'none';
end
ax.XLim = [-1*max(max(abs(h.XData))), max(max(abs(h.XData)))];
ax.YLim = [-1*max(max(abs(h.YData))), max(max(abs(h.YData)))];
ax.DataAspectRatio = [1, 1, 1];
% Close the figure
close(Fig)

end